# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: chimp
