name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | base64 --decode > ssh_private.key
        chmod 400 ssh_private.key
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build app
      run: mvn package -P build
    - name: Update app
      run: |
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh_private.key ec2-user@54.78.42.221 git -C /home/ec2-user/backend pull --ff-only